name: Go Vet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          - go-version: "1.19"

      - name: Deps
        run: go mod tidy

      - name: Analyze
        run: go vet ./...
